site_name: iDEC 2022 | OriGeneNation (formerly DU_DTU_NSUT-Delhi)

theme:
  name: material
  logo: img/idec-wiki-logo-white-bg.png
  favicon: img/idec-wiki-logo.png

  palette:
    primary: light purple
    accent: purple 

  features:
    - navigation.sections

markdown_extensions:
  - footnotes

  # For MathJax
  - pymdownx.arithmatex:
      generic: true

  # For buttons and image control
  - attr_list

extra_javascript:
  # For MathJax: https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  # For sortable data tables: https://squidfunk.github.io/mkdocs-material/reference/data-tables/
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

edit_uri: blob/main/docs/

repo_url: https://github.com/idec-teams/2022_DU_DTU_NSUT-Delhi

copyright: Copyright &copy; 2022 iDEC. CC-BY-4.0 | The International Directed Evolution Competition (iDEC) is a Scottish Charitable Incorporate Organisation (SCIO), registered in Scotland, with charity numberï¼šSC050826

nav:
  - Team: team.md 
  - Project:
      - Ideation:
          - Introduction: index.md
          - Background: project/background.md
      - Findings:
          - Results: project/results.md
          - Discussion and Path Ahead: project/discussion.md
      - Documentation:
          - Protocols: documentation/protocols.md
          - Supplementary information: project/Supplementary.md
      - References: project/references.md